### ISSUE TITLE
Correction Orthographe 

### ISSUE THREAD

**Issue by fhryan** [julkwel/sekoliko#11]
Barre de Menu : 

Tableaux de bord - > Tableau de bord
User Guide -> Guide d'utilisateur 
Information -> Informations
Nouveau Utilisateur -> Nouvel Etudiant 
Nouveau Etudiant -> Nouvel Etudiant
Niveau -> Niveaux
Classe -> Classes
Nouveau classes -> Nouvelle Classe
Nouveau matière -> Nouvelle Matière
Nouveau Etudiant -> Nouvel Etudiant 
Salle -> Salles 
Liste salle -> Liste des salles
Nouveau salle -> Nouvelle Salle
Discpline -> Disciplines 
Liste discipline - > Liste des Disciplines 
Nouveau Discipline -> Nouvelle Discipline

User Guide ( Guide d'Utilisateur) : 

Liste des Guides -> Guide d'utilisateur
-Pour ajouter un étudiant, allez dans "Classe>Liste des étudiants>Créer un étudiant" ou "Utilisateurs>Nouvel Etudiant" 
-Pour rechercher un étudiant ou un utilisateur, allez dans "Utilisateurs>Recherche Utilisateur" 
- Avant d'ajouter une matière, ajoutez un prof
- Pour voir les matières, les emplois du temps, et la liste des étudiants, allez dans "Classe>Liste des Classes"
- Pour ajouter un utilisateur, allez dans "Utilisateur>Nouvel Utilisateur"

**Comment by julkwel** [comment]
Merci beaucoup pour les retours | @chrys-elrak  @vonyms

**Comment by julkwel** [comment]
fix on #21
