### ISSUE TITLE
ERREUR 500 Satria nanao login t@ adresse : "test" sy mdp : "test" aho .. Mety efa hitanareo fa juste participation ako voalohany zay

### ISSUE THREAD

**Issue by TinahFanomezantsoa** [julkwel/sekoliko#13]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by julkwel** [comment]
Thanks
