### ISSUE TITLE
Slack group request.

### ISSUE THREAD

**Issue by t-harison** [julkwel/sekoliko#20]
@julkwel It is possible to create a Slack group for the project?

**Comment by julkwel** [comment]
Ok

**Comment by julkwel** [comment]
https://join.slack.com/t/sekoliko-project/shared_invite/enQtNTk3MDkxODEyMTY1LTM4ZGVlNDExMmY4ZWRhZDZkYzQ3OWRkZmNmZGU3YmQ4MzllM2Q0ODQzZjZkZWY4YjhlMjQ0NDY5MGI5YTYzZjY
