### ISSUE TITLE
Disabling all unworking links

### ISSUE THREAD

**Issue by hantsaniala** [julkwel/sekoliko#40]
There is some links that doesn't work but still available.

**Comment by julkwel** [comment]
Could you reproduce and send a screenshot ?

**Comment by hantsaniala** [comment]
I think for now, these are the only unworking link but maybe for next update if the feature is still not done, it's a good idea to disable then until. 

![Opera Snapshot_2019-04-03_160745_www sekoliko org](https://user-images.githubusercontent.com/8157490/55481444-1b1d5380-562b-11e9-87bc-ca310d298f9e.png)
- Paramètres
- Journal des activités

**Comment by julkwel** [comment]
Fix at 8c6d92d
