### ISSUE TITLE
Correction Orthographe - Page d'authentification

### ISSUE THREAD

**Issue by fhryan** [julkwel/sekoliko#9]
src/Bundle/User/Resources/views/Security/login.html.twig

             <input type="text"  name="_username" id="username" class="form-control form-control-user"  aria-describedby="emailHelp" placeholder="Entrez votre adresse e-mail">

             <a class="small" href="{{ path('sk_resetting_password') }}">Mot de passe oublié ?</a>

**Comment by julkwel** [comment]
@vonyms

**Comment by julkwel** [comment]
> src/Bundle/User/Resources/views/Security/login.html.twig
> 
> ```
>          <input type="text"  name="_username" id="username" class="form-control form-control-user"  aria-describedby="emailHelp" placeholder="Entrez votre adresse e-mail">
> 
>          <a class="small" href="{{ path('sk_resetting_password') }}">Mot de passe oublié ?</a>
> ```

fix on #23
