### ISSUE TITLE
Error 500 when browsing to scolarite list in dashboard

### ISSUE THREAD

**Issue by SylvanoTombo** [julkwel/sekoliko#92]
**Describe the bug**
Error 500 when browsing to scolarite list in dashboard
Error: Call to a member function getId() on null

**To Reproduce**
1. clone the project
2. follow the installation steps
3. login
4. go to scolarite list in dashboard
5. See error 500

**Expected behavior**

**Screenshots**
![Screenshot_2019-11-27_21-20-18](https://user-images.githubusercontent.com/40351002/69749562-d1eeb680-115b-11ea-831e-515fc040b2e4.png)

**Comment by julkwel** [comment]
Why this issues happened ?
User must be have a schoolYear.

**Step to fix this issues**

Create new school year.

Edit manually the user in your database , assigned user to one school year.

But i'm trying to fix this , thanks .💥

**Comment by julkwel** [comment]
will be fixed on [this](https://github.com/julkwel/sekoliko/commit/3a758c55a57357b6d3574c1e268531017d2eb69b)
